services:
  
  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
    name: "postgres-data"
    driver: local
