services:
  
  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:8.0.3
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  postgres_data:
    name: "postgres-data"
    driver: local

  redis_data:
    name: "redis-data"
    driver: local
